baseURL = "https://lakewood.urbanism-guide.com/"
title = "Lakewood Urbanism Guide"

[module]
[[module.imports]]
path = "github.com/prestomation/urbanism-guide-core"

[params]
  description = "A practical guide for Lakewood urbanists and advocates. Understand the issues, learn the terms, and show up ready to contribute."
  goatCounterCode = "lakewood-urbanism-guide"
  BookRepo = "https://github.com/prestomation/lakewood-urbanism-guide"
  BookEditPath = "edit/main/content"
