name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    permissions:
      contents: write
      pull-requests: write
    uses: prestomation/urbanism-guide-core/.github/workflows/pr-preview.yml@v0.3.1
    with:
      timezone: "America/New_York"
      base_url: "https://lakewood.urbanism-guide.com"
